# Generated by Django 4.2.5 on 2023-10-10 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('cod_ISBN', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=30)),
                ('blurb', models.TextField()),
                ('published', models.DateTimeField()),
                ('number_pages', models.IntegerField()),
                ('cover', models.FileField(upload_to='')),
                ('rating', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Books',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Discussions',
            fields=[
                ('id_discussion', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('cod_ISBN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmarks.books')),
            ],
            options={
                'verbose_name_plural': 'Discussions',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id_gender', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Genres',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_birth', models.DateField()),
                ('points', models.IntegerField(blank=True, null=True)),
                ('favorite_books', models.ManyToManyField(blank=True, to='bookmarks.books')),
                ('genres', models.ManyToManyField(blank=True, to='bookmarks.genres')),
            ],
            options={
                'verbose_name_plural': 'Users',
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='TaggedDiscussions',
            fields=[
                ('id_tagged', models.AutoField(primary_key=True, serialize=False)),
                ('id_discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmarks.discussions')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmarks.users')),
            ],
            options={
                'verbose_name_plural': 'Tagged Discussions',
                'ordering': ['id_tagged'],
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id_review', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('rating', models.FloatField()),
                ('date', models.DateField()),
                ('cod_ISBN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmarks.books')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmarks.users')),
            ],
            options={
                'verbose_name_plural': 'Reviews',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='LikedDiscussions',
            fields=[
                ('id_liked', models.AutoField(primary_key=True, serialize=False)),
                ('id_discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmarks.discussions')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmarks.users')),
            ],
            options={
                'verbose_name_plural': 'Liked Discussions',
                'ordering': ['id_liked'],
            },
        ),
        migrations.CreateModel(
            name='LikedComments',
            fields=[
                ('id_liked', models.AutoField(primary_key=True, serialize=False)),
                ('id_discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmarks.discussions')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmarks.users')),
            ],
            options={
                'verbose_name_plural': 'Liked Comments',
                'ordering': ['id_liked'],
            },
        ),
        migrations.AddField(
            model_name='discussions',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmarks.users'),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id_comment', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('cod_ISBN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmarks.books')),
                ('id_related_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookmarks.comments')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmarks.users')),
            ],
            options={
                'verbose_name_plural': 'Comments',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='books',
            name='generos',
            field=models.ManyToManyField(to='bookmarks.genres'),
        ),
    ]
