# Generated by Django 4.2.5 on 2023-10-10 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='favorite_books',
            field=models.ManyToManyField(to='bookmarks.books'),
        ),
        migrations.AlterField(
            model_name='users',
            name='genres',
            field=models.ManyToManyField(to='bookmarks.genres'),
        ),
    ]
