# Generated by Django 4.2.5 on 2023-10-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0003_rename_generos_books_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='favorite_books',
            field=models.ManyToManyField(blank=True, to='bookmarks.books'),
        ),
        migrations.AlterField(
            model_name='users',
            name='genres',
            field=models.ManyToManyField(blank=True, to='bookmarks.genres'),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
