# Generated by Django 4.2.5 on 2023-10-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0005_users_active_users_created_users_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='date_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
