# Generated by Django 4.2.5 on 2023-10-12 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0008_rename_books_book_rename_discussions_discussion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likedcomments',
            name='ab',
        ),
    ]
