# Generated by Django 4.2.5 on 2023-10-20 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0014_remove_book_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='cod_ISBN',
        ),
        migrations.AddField(
            model_name='comments',
            name='id_discussion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bookmarks.discussion'),
            preserve_default=False,
        ),
    ]
