# Generated by Django 4.2.5 on 2023-10-23 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0016_alter_book_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likedcomments',
            name='id_discussion',
        ),
        migrations.AddField(
            model_name='likedcomments',
            name='id_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bookmarks.comments'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
